/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.html5.shared;


public class FavouriteBusStationListMarshaller_Helper extends bz.davide.dmxmljson.marshalling.Marshaller
{
   protected FavouriteBusStationListMarshaller_Helper()
   {
      this.putClassMarshaller("it.bz.tis.sasabus.html5.shared.FavouriteBusStationList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // busStationIds
            value = ((it.bz.tis.sasabus.html5.shared.FavouriteBusStationList)obj).busStationIds;
            if (value == null)
               structure.property("busStationIds").nullValue();
            else
            {
               // Hashmap
               java.util.HashMap hashMap = (java.util.HashMap)value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("busStationIds").array();        
               java.util.ArrayList keySelList = new java.util.ArrayList(hashMap.keySet());
               java.util.Collections.sort(keySelList);
               for (Object key: keySelList) {
                  bz.davide.dmxmljson.marshalling.Array item = array.item().array(); 
                  item.item().string((String)key);
                  item.item().string((String)hashMap.get(key));
               }
            }
            if (!superClass)
               structure.close();
         }
      });

   }
}
