/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.html5.shared;


public class SASAbusUnmarshaller_Helper extends it.bz.tis.sasabus.html5.shared.ui.titlebar.SASAbusUnmarshaller_Helper
{
   protected SASAbusUnmarshaller_Helper()
   {
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.SASAbusWebPage$InitParameters", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters  ret){
            // custom
            if (ret.custom != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPage$InitParameters.custom");
            // homePageCustomFragment
            if (ret.homePageCustomFragment != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPage$InitParameters.homePageCustomFragment");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.SASAbusWebPage$InitParameters", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters ret = new it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.SASAbusWebPage$InitParameters").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.SASAbusWebPage$InitParameters", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // custom
            if ((value = structure.property("custom")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters)obj).custom = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters)obj).custom = (it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("BusStationCustomViewAndI18N"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters)obj).custom = (it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)o;
                  }
               }
            // homePageCustomFragment
            if ((value = structure.property("homePageCustomFragment")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters)obj).homePageCustomFragment = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters)obj).homePageCustomFragment = (it.bz.tis.sasabus.html5.shared.HomePageCustomFragment)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("HomePageCustomFragment"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPage.InitParameters)obj).homePageCustomFragment = (it.bz.tis.sasabus.html5.shared.HomePageCustomFragment)o;
                  }
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.SASAbusI18N", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.SASAbusI18N>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.SASAbusI18N  ret){
            // language
            if (ret.language != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusI18N.language");
            // translations
            if (ret.translations != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusI18N.translations");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.SASAbusI18N", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.SASAbusI18N ret = new it.bz.tis.sasabus.html5.shared.SASAbusI18N();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.SASAbusI18N").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.SASAbusI18N", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // language
            if ((value = structure.property("language")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18N)obj).language = null;
               else
               {
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18N)obj).language = value.string();
               }
            // translations
            if ((value = structure.property("translations")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18N)obj).translations = null;
               else
               {
                  bz.davide.dmxmljson.unmarshalling.Array arr = value.array();        
                  arr.open();        
                  it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText[] arrayList = new it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText[arr.length()];       
                  for (int i = 0; i < arrayList.length; i++) {                       
                     value = arr.nextItem();                                       
                     if (value.isNull())                                           
                        arrayList[i] = null;                                       
                     else                                                          
                     {                                                                   
                        bz.davide.dmxmljson.unmarshalling.Structure tmpStructure = value.structure();
                        String refid = tmpStructure.getRefId();    
                        if (refid != null)                              
                           arrayList[i] = (it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText)(identities.get(refid));                                                
                        else {
                           Object o = newInstance(tmpStructure.getRuntimeClassName("SASAbusI18NKeyLocalizedText"));              
                           internalUnmarschall(tmpStructure, o.getClass().getName(), o, identities); 
                           arrayList[i] = (it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText)(o);                                                
                        }
                     }                                                                   
                  }                                                                   
                  arr.close();        
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18N)obj).translations = arrayList;
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText  ret){
            // introText
            if (ret.introText != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText.introText");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText ret = new it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // introText
            if ((value = structure.property("introText")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText)obj).introText = null;
               else
               {
                  ((it.bz.tis.sasabus.html5.shared.HomePageCustomIntroText)obj).introText = value.string();
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N  ret){
            // busStationCustomView
            if (ret.busStationCustomView != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N.busStationCustomView");
            // i18n
            if (ret.i18n != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N.i18n");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N ret = new it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // busStationCustomView
            if ((value = structure.property("busStationCustomView")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)obj).busStationCustomView = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)obj).busStationCustomView = (it.bz.tis.sasabus.html5.shared.BusStationCustomView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("BusStationCustomView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)obj).busStationCustomView = (it.bz.tis.sasabus.html5.shared.BusStationCustomView)o;
                  }
               }
            // i18n
            if ((value = structure.property("i18n")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)obj).i18n = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)obj).i18n = (it.bz.tis.sasabus.html5.shared.SASAbusI18N)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("SASAbusI18N"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)obj).i18n = (it.bz.tis.sasabus.html5.shared.SASAbusI18N)o;
                  }
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler  ret){
            // cover
            if (ret.cover != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.cover");
            // custom
            if (ret.custom != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.custom");
            // homePanel
            if (ret.homePanel != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.homePanel");
            // map
            if (ret.map != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.map");
            // menu
            if (ret.menu != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.menu");
            // navigationPanel
            if (ret.navigationPanel != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.navigationPanel");
            // wrapper
            if (ret.wrapper != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler.wrapper");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler ret = new it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // cover
            if ((value = structure.property("cover")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).cover = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).cover = (bz.davide.dmweb.shared.view.DivView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DivView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).cover = (bz.davide.dmweb.shared.view.DivView)o;
                  }
               }
            // custom
            if ((value = structure.property("custom")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).custom = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).custom = (it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("BusStationCustomViewAndI18N"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).custom = (it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N)o;
                  }
               }
            // homePanel
            if ((value = structure.property("homePanel")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).homePanel = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).homePanel = (it.bz.tis.sasabus.html5.shared.ui.HomePanel)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("HomePanel"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).homePanel = (it.bz.tis.sasabus.html5.shared.ui.HomePanel)o;
                  }
               }
            // map
            if ((value = structure.property("map")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).map = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).map = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("SASAbusMap"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).map = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)o;
                  }
               }
            // menu
            if ((value = structure.property("menu")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).menu = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).menu = (it.bz.tis.sasabus.html5.shared.ui.menu.Menu)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("Menu"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).menu = (it.bz.tis.sasabus.html5.shared.ui.menu.Menu)o;
                  }
               }
            // navigationPanel
            if ((value = structure.property("navigationPanel")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).navigationPanel = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).navigationPanel = (bz.davide.dmweb.shared.view.DMHashNavigationPanel)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DMHashNavigationPanel"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).navigationPanel = (bz.davide.dmweb.shared.view.DMHashNavigationPanel)o;
                  }
               }
            // wrapper
            if ((value = structure.property("wrapper")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).wrapper = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).wrapper = (bz.davide.dmweb.shared.view.DivView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DivView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).wrapper = (bz.davide.dmweb.shared.view.DivView)o;
                  }
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText  ret){
            // key
            if (ret.key != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText.key");
            // text
            if (ret.text != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText.text");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText ret = new it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // key
            if ((value = structure.property("key")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText)obj).key = null;
               else
               {
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText)obj).key = value.string();
               }
            // text
            if ((value = structure.property("text")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText)obj).text = null;
               else
               {
                  ((it.bz.tis.sasabus.html5.shared.SASAbusI18NKeyLocalizedText)obj).text = value.string();
               }
            structure.close();
         }
      });

   }
}
