/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.html5.shared;


public class SASAbusWidgetMarshaller_Helper extends it.bz.tis.sasabus.html5.shared.ui.titlebar.SASAbusWidgetMarshaller_Helper
{
   protected SASAbusWidgetMarshaller_Helper()
   {
      this.putClassMarshaller("it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // cover
            value = ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).cover;
            if (value == null)
               structure.property("cover").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.DMFlowPanel", structure.property("cover").structure(), identities, seq, false);
            }
            // homePanel
            value = ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).homePanel;
            if (value == null)
               structure.property("homePanel").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.html5.shared.ui.HomePanel", structure.property("homePanel").structure(), identities, seq, false);
            }
            // map
            value = ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).map;
            if (value == null)
               structure.property("map").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap", structure.property("map").structure(), identities, seq, false);
            }
            // menu
            value = ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).menu;
            if (value == null)
               structure.property("menu").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.html5.shared.ui.menu.Menu", structure.property("menu").structure(), identities, seq, false);
            }
            // navigationPanel
            value = ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).navigationPanel;
            if (value == null)
               structure.property("navigationPanel").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.DMHashNavigationPanel", structure.property("navigationPanel").structure(), identities, seq, false);
            }
            // wrapper
            value = ((it.bz.tis.sasabus.html5.shared.SASAbusWebPageAttachHandler)obj).wrapper;
            if (value == null)
               structure.property("wrapper").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.DMFlowPanel", structure.property("wrapper").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });

   }
}
