/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.html5.shared.ui.map;


public class SASAbusMarshaller_Helper extends it.bz.tis.sasabus.backend.shared.SASAbusMarshaller_Helper
{
   protected SASAbusMarshaller_Helper()
   {
      this.putClassMarshaller("it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            internalMarschall(obj, "bz.davide.dmweb.shared.view.DivView", "N/A",structure, identities, seq, true);
            Object value;
            // areaList
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).areaList;
            if (value == null)
               structure.property("areaList").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.backend.shared.AreaList", structure.property("areaList").structure(), identities, seq, false);
            }
            // close
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).close;
            if (value == null)
               structure.property("close").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.ButtonView", structure.property("close").structure(), identities, seq, false);
            }
            // controls
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).controls;
            if (value == null)
               structure.property("controls").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.DivView", structure.property("controls").structure(), identities, seq, false);
            }
            // custom
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).custom;
            if (value == null)
               structure.property("custom").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.html5.shared.BusStationCustomViewAndI18N", structure.property("custom").structure(), identities, seq, false);
            }
            // gpsIcon
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).gpsIcon;
            if (value == null)
               structure.property("gpsIcon").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.html5.shared.ui.icon.Icon", structure.property("gpsIcon").structure(), identities, seq, false);
            }
            // i18n
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).i18n;
            if (value == null)
               structure.property("i18n").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"it.bz.tis.sasabus.html5.shared.SASAbusI18N", structure.property("i18n").structure(), identities, seq, false);
            }
            // mapDiv
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).mapDiv;
            if (value == null)
               structure.property("mapDiv").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.DivView", structure.property("mapDiv").structure(), identities, seq, false);
            }
            // navigationPanel
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).navigationPanel;
            if (value == null)
               structure.property("navigationPanel").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.DMHashNavigationPanel", structure.property("navigationPanel").structure(), identities, seq, false);
            }
            // overwievMap
            value = ((it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)obj).overwievMap;
            if (value == null)
               structure.property("overwievMap").nullValue();
            else
            {
                     internalMarschall(value, value.getClass().getName(),"bz.davide.dmweb.shared.view.DivView", structure.property("overwievMap").structure(), identities, seq, false);
            }
            if (!superClass)
               structure.close();
         }
      });

   }
}
