/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.backend.shared;


public class SASAbusWidgetUnmarshaller_Helper extends bz.davide.dmxmljson.unmarshalling.Unmarshaller
{
   protected SASAbusWidgetUnmarshaller_Helper()
   {
      this.putInstanceFactory("it.bz.tis.sasabus.backend.shared.AreaList", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.backend.shared.AreaList((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.backend.shared.AreaList", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // areas
            if ((value = structure.property("areas")) != null)
               if (value.isNull())
                  ((AreaList)obj).areas = null;
               else
               {
                  bz.davide.dmxmljson.unmarshalling.Array arr = value.array();        
                  java.util.ArrayList arrayList = new java.util.ArrayList();       
                  while ((value = arr.nextItem()) != null) {                       
                     if (value.isNull())                                           
                        arrayList.add(null);                                       
                     else                                                          
                     {                                                                   
                        String refid = value.structure().getRefId();    
                        if (refid != null)                              
                           arrayList.add(identities.get(refid));                                                
                        else {
                           Object o = newInstance(value.structure().getRuntimeClassName("Area"));              
                           internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                           arrayList.add(o);                                                
                        }
                     }                                                                   
                  }                                                                   
                  ((AreaList)obj).areas = (it.bz.tis.sasabus.backend.shared.Area[])arrayList.toArray(new it.bz.tis.sasabus.backend.shared.Area[0]);
               }
            // lastModified
            if ((value = structure.property("lastModified")) != null)
               if (value.isNull())
                  new RuntimeException("Impossibile value for primitive type");
               else
               {
                  ((AreaList)obj).lastModified = value.integer();
               }
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.backend.shared.Area", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.backend.shared.Area((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.backend.shared.Area", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // busLines
            if ((value = structure.property("busLines")) != null)
               if (value.isNull())
                  ((Area)obj).busLines = null;
               else
               {
                  bz.davide.dmxmljson.unmarshalling.Array arr = value.array();        
                  java.util.ArrayList arrayList = new java.util.ArrayList();       
                  while ((value = arr.nextItem()) != null) {                       
                     if (value.isNull())                                           
                        arrayList.add(null);                                       
                     else                                                          
                     {                                                                   
                        String refid = value.structure().getRefId();    
                        if (refid != null)                              
                           arrayList.add(identities.get(refid));                                                
                        else {
                           Object o = newInstance(value.structure().getRuntimeClassName("BusLine"));              
                           internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                           arrayList.add(o);                                                
                        }
                     }                                                                   
                  }                                                                   
                  ((Area)obj).busLines = (it.bz.tis.sasabus.backend.shared.BusLine[])arrayList.toArray(new it.bz.tis.sasabus.backend.shared.BusLine[0]);
               }
            // id
            if ((value = structure.property("id")) != null)
               if (value.isNull())
                  new RuntimeException("Impossibile value for primitive type");
               else
               {
                  ((Area)obj).id = (int)value.integer();
               }
            // name_de
            if ((value = structure.property("name_de")) != null)
               if (value.isNull())
                  ((Area)obj).name_de = null;
               else
               {
                  ((Area)obj).name_de = value.string();
               }
            // name_it
            if ((value = structure.property("name_it")) != null)
               if (value.isNull())
                  ((Area)obj).name_it = null;
               else
               {
                  ((Area)obj).name_it = value.string();
               }
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.backend.shared.BusLine", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.backend.shared.BusLine((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.backend.shared.BusLine", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // area
            if ((value = structure.property("area")) != null)
               if (value.isNull())
                  ((BusLine)obj).area = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((BusLine)obj).area = (it.bz.tis.sasabus.backend.shared.Area)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("Area"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((BusLine)obj).area = (it.bz.tis.sasabus.backend.shared.Area)o;
                  }
               }
            // busStops
            if ((value = structure.property("busStops")) != null)
               if (value.isNull())
                  ((BusLine)obj).busStops = null;
               else
               {
                  bz.davide.dmxmljson.unmarshalling.Array arr = value.array();        
                  java.util.ArrayList arrayList = new java.util.ArrayList();       
                  while ((value = arr.nextItem()) != null) {                       
                     if (value.isNull())                                           
                        arrayList.add(null);                                       
                     else                                                          
                     {                                                                   
                        String refid = value.structure().getRefId();    
                        if (refid != null)                              
                           arrayList.add(identities.get(refid));                                                
                        else {
                           Object o = newInstance(value.structure().getRuntimeClassName("BusStop"));              
                           internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                           arrayList.add(o);                                                
                        }
                     }                                                                   
                  }                                                                   
                  ((BusLine)obj).busStops = (it.bz.tis.sasabus.backend.shared.BusStop[])arrayList.toArray(new it.bz.tis.sasabus.backend.shared.BusStop[0]);
               }
            // id
            if ((value = structure.property("id")) != null)
               if (value.isNull())
                  new RuntimeException("Impossibile value for primitive type");
               else
               {
                  ((BusLine)obj).id = (int)value.integer();
               }
            // number
            if ((value = structure.property("number")) != null)
               if (value.isNull())
                  ((BusLine)obj).number = null;
               else
               {
                  ((BusLine)obj).number = value.string();
               }
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.backend.shared.BusStop", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.backend.shared.BusStop((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.backend.shared.BusStop", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // busStation
            if ((value = structure.property("busStation")) != null)
               if (value.isNull())
                  ((BusStop)obj).busStation = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((BusStop)obj).busStation = (it.bz.tis.sasabus.backend.shared.BusStation)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("BusStation"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((BusStop)obj).busStation = (it.bz.tis.sasabus.backend.shared.BusStation)o;
                  }
               }
            // id
            if ((value = structure.property("id")) != null)
               if (value.isNull())
                  new RuntimeException("Impossibile value for primitive type");
               else
               {
                  ((BusStop)obj).id = (int)value.integer();
               }
            // lat
            if ((value = structure.property("lat")) != null)
               if (value.isNull())
                  new RuntimeException("Impossibile value for primitive type");
               else
               {
                  ((BusStop)obj).lat = value.decimal();
               }
            // lon
            if ((value = structure.property("lon")) != null)
               if (value.isNull())
                  new RuntimeException("Impossibile value for primitive type");
               else
               {
                  ((BusStop)obj).lon = value.decimal();
               }
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.backend.shared.BusStation", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.backend.shared.BusStation((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.backend.shared.BusStation", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // busLines
            if ((value = structure.property("busLines")) != null)
               if (value.isNull())
                  ((BusStation)obj).busLines = null;
               else
               {
                  bz.davide.dmxmljson.unmarshalling.Array arr = value.array();        
                  java.util.ArrayList arrayList = new java.util.ArrayList();       
                  while ((value = arr.nextItem()) != null) {                       
                     if (value.isNull())                                           
                        arrayList.add(null);                                       
                     else                                                          
                     {                                                                   
                        String refid = value.structure().getRefId();    
                        if (refid != null)                              
                           arrayList.add(identities.get(refid));                                                
                        else {
                           Object o = newInstance(value.structure().getRuntimeClassName("BusLine"));              
                           internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                           arrayList.add(o);                                                
                        }
                     }                                                                   
                  }                                                                   
                  ((BusStation)obj).busLines = (it.bz.tis.sasabus.backend.shared.BusLine[])arrayList.toArray(new it.bz.tis.sasabus.backend.shared.BusLine[0]);
               }
            // busStops
            if ((value = structure.property("busStops")) != null)
               if (value.isNull())
                  ((BusStation)obj).busStops = null;
               else
               {
                  bz.davide.dmxmljson.unmarshalling.Array arr = value.array();        
                  java.util.ArrayList arrayList = new java.util.ArrayList();       
                  while ((value = arr.nextItem()) != null) {                       
                     if (value.isNull())                                           
                        arrayList.add(null);                                       
                     else                                                          
                     {                                                                   
                        String refid = value.structure().getRefId();    
                        if (refid != null)                              
                           arrayList.add(identities.get(refid));                                                
                        else {
                           Object o = newInstance(value.structure().getRuntimeClassName("BusStop"));              
                           internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                           arrayList.add(o);                                                
                        }
                     }                                                                   
                  }                                                                   
                  ((BusStation)obj).busStops = (it.bz.tis.sasabus.backend.shared.BusStop[])arrayList.toArray(new it.bz.tis.sasabus.backend.shared.BusStop[0]);
               }
            // id
            if ((value = structure.property("id")) != null)
               if (value.isNull())
                  ((BusStation)obj).id = null;
               else
               {
                  ((BusStation)obj).id = value.string();
               }
            // name_de
            if ((value = structure.property("name_de")) != null)
               if (value.isNull())
                  ((BusStation)obj).name_de = null;
               else
               {
                  ((BusStation)obj).name_de = value.string();
               }
            // name_it
            if ((value = structure.property("name_it")) != null)
               if (value.isNull())
                  ((BusStation)obj).name_it = null;
               else
               {
                  ((BusStation)obj).name_it = value.string();
               }
         }
      });

   }
}
