/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.html5.shared.ui;


public class SASAbusWidgetUnmarshaller_Helper extends it.bz.tis.sasabus.html5.shared.ui.menu.SASAbusWidgetUnmarshaller_Helper
{
   protected SASAbusWidgetUnmarshaller_Helper()
   {
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.ui.HomePanel", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.ui.HomePanel>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.ui.HomePanel  ret){
            // favouriteBusStationListPanel
            if (ret.favouriteBusStationListPanel != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.HomePanel.favouriteBusStationListPanel");
            // favouriteContainer
            if (ret.favouriteContainer != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.HomePanel.favouriteContainer");
            // introText
            if (ret.introText != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.HomePanel.introText");
            // map
            if (ret.map != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.HomePanel.map");
            emptyObjectCheck.get("bz.davide.dmweb.shared.view.DivView").check(ret);
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.HomePanel", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.ui.HomePanel ret = new it.bz.tis.sasabus.html5.shared.ui.HomePanel();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.ui.HomePanel").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.HomePanel", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            internalUnmarschall(structure, "bz.davide.dmweb.shared.view.DivView", obj, identities);
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // favouriteBusStationListPanel
            if ((value = structure.property("favouriteBusStationListPanel")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).favouriteBusStationListPanel = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).favouriteBusStationListPanel = (it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("FavouriteBusStationListPanel"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).favouriteBusStationListPanel = (it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)o;
                  }
               }
            // favouriteContainer
            if ((value = structure.property("favouriteContainer")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).favouriteContainer = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).favouriteContainer = (bz.davide.dmweb.shared.view.DivView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DivView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).favouriteContainer = (bz.davide.dmweb.shared.view.DivView)o;
                  }
               }
            // introText
            if ((value = structure.property("introText")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).introText = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).introText = (bz.davide.dmweb.shared.view.DivView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DivView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).introText = (bz.davide.dmweb.shared.view.DivView)o;
                  }
               }
            // map
            if ((value = structure.property("map")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).map = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).map = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("SASAbusMap"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.HomePanel)obj).map = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)o;
                  }
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.ui.AboutPanel", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.ui.AboutPanel>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.ui.AboutPanel  ret){
            emptyObjectCheck.get("bz.davide.dmweb.shared.view.DivView").check(ret);
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.AboutPanel", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.ui.AboutPanel ret = new it.bz.tis.sasabus.html5.shared.ui.AboutPanel();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.ui.AboutPanel").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.AboutPanel", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            internalUnmarschall(structure, "bz.davide.dmweb.shared.view.DivView", obj, identities);
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler  ret){
            // aboutPanel
            if (ret.aboutPanel != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler.aboutPanel");
            // thirdPartyLicenses
            if (ret.thirdPartyLicenses != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler.thirdPartyLicenses");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler ret = new it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // aboutPanel
            if ((value = structure.property("aboutPanel")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler)obj).aboutPanel = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler)obj).aboutPanel = (it.bz.tis.sasabus.html5.shared.ui.AboutPanel)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("AboutPanel"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler)obj).aboutPanel = (it.bz.tis.sasabus.html5.shared.ui.AboutPanel)o;
                  }
               }
            // thirdPartyLicenses
            if ((value = structure.property("thirdPartyLicenses")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler)obj).thirdPartyLicenses = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler)obj).thirdPartyLicenses = (bz.davide.dmweb.shared.view.DivView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DivView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelCloseHandler)obj).thirdPartyLicenses = (bz.davide.dmweb.shared.view.DivView)o;
                  }
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses  ret){
            // licensesPanel
            if (ret.licensesPanel != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses.licensesPanel");
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses ret = new it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // licensesPanel
            if ((value = structure.property("licensesPanel")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses)obj).licensesPanel = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses)obj).licensesPanel = (bz.davide.dmweb.shared.view.DivView)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DivView"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.AboutPanelShow3rdPartyLicenses)obj).licensesPanel = (bz.davide.dmweb.shared.view.DivView)o;
                  }
               }
            structure.close();
         }
      });
      this.emptyObjectCheck.put("it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel>() {
         @Override public void check(it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel  ret){
            // areaList
            if (ret.areaList != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel.areaList");
            // map
            if (ret.map != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel.map");
            // navigationPanel
            if (ret.navigationPanel != null)
               throw new RuntimeException("The constructor initialized the field it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel.navigationPanel");
            emptyObjectCheck.get("bz.davide.dmweb.shared.view.DivView").check(ret);
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel ret = new it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel();
            emptyObjectCheck.get("it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            internalUnmarschall(structure, "bz.davide.dmweb.shared.view.DivView", obj, identities);
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // areaList
            if ((value = structure.property("areaList")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).areaList = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).areaList = (it.bz.tis.sasabus.backend.shared.AreaList)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("AreaList"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).areaList = (it.bz.tis.sasabus.backend.shared.AreaList)o;
                  }
               }
            // map
            if ((value = structure.property("map")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).map = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).map = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("SASAbusMap"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).map = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)o;
                  }
               }
            // navigationPanel
            if ((value = structure.property("navigationPanel")) != null)
               if (value.isNull())
                  ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).navigationPanel = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).navigationPanel = (bz.davide.dmweb.shared.view.DMHashNavigationPanel)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("DMHashNavigationPanel"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((it.bz.tis.sasabus.html5.shared.ui.FavouriteBusStationListPanel)obj).navigationPanel = (bz.davide.dmweb.shared.view.DMHashNavigationPanel)o;
                  }
               }
            structure.close();
         }
      });

   }
}
