/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.bz.tis.sasabus.html5.shared.ui.titlebar;


public class SASAbusWidgetUnmarshaller_Helper extends bz.davide.dmweb.shared.i18n.SASAbusWidgetUnmarshaller_Helper
{
   protected SASAbusWidgetUnmarshaller_Helper()
   {
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.titlebar.TitleBarMenuClickHandler", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.html5.shared.ui.titlebar.TitleBarMenuClickHandler((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.titlebar.TitleBarMenuClickHandler", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // menu
            if ((value = structure.property("menu")) != null)
               if (value.isNull())
                  ((TitleBarMenuClickHandler)obj).menu = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((TitleBarMenuClickHandler)obj).menu = (it.bz.tis.sasabus.html5.shared.ui.menu.Menu)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("Menu"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((TitleBarMenuClickHandler)obj).menu = (it.bz.tis.sasabus.html5.shared.ui.menu.Menu)o;
                  }
               }
         }
      });
      this.putInstanceFactory("it.bz.tis.sasabus.html5.shared.ui.titlebar.TitleBarMapClickHandler", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            return new it.bz.tis.sasabus.html5.shared.ui.titlebar.TitleBarMapClickHandler((Void)null);
         }
      });

      this.putClassUnmarshaller("it.bz.tis.sasabus.html5.shared.ui.titlebar.TitleBarMapClickHandler", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // mapWidget
            if ((value = structure.property("mapWidget")) != null)
               if (value.isNull())
                  ((TitleBarMapClickHandler)obj).mapWidget = null;
               else
               {
                  String refid = value.structure().getRefId();    
                  if (refid != null)                              
                     ((TitleBarMapClickHandler)obj).mapWidget = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)identities.get(refid);
                  else {
                     Object o = newInstance(value.structure().getRuntimeClassName("SASAbusMap"));              
                     internalUnmarschall(value.structure(), o.getClass().getName(), o, identities); 
                     ((TitleBarMapClickHandler)obj).mapWidget = (it.bz.tis.sasabus.html5.shared.ui.map.SASAbusMap)o;
                  }
               }
         }
      });

   }
}
